let allarr=[ {
    title:"Charcoal Facewash for oil control, 100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-face-wash-1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:249,
    rating:4.8,
},
{
    title:"Tea Tree Facewash for acne and pimples, 100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/t/e/tea-tree-face-wash-1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:249,
    rating:4.7,
},
{
    title:"Ubtan Face Wash with Turmeric & Saffron for Tan Removal-100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-face-wash_1_1_1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:249,
    rating:4.8,
},
{
    title:"Aloe Vera Face Wash with Aloe Vera & Ashwagandha for a Youthful Glow-100 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/l/aloevera-fw-1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:259,
    rating:4.8,
},
{
    title:"Oil-Free Face Wash with Apple Cider Vinegar & Salicylic Acid for Acne-Prone Skin-100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/i/oil-free-face-wash_1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:249,
    rating:4.8,
},
{
    title:"Aqua Glow Skin Refreshing Combo for Hydrated & Fresh Skin",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/o/combo_3.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:1065,
    rating:4.7,
},
{
    title:"Gentle Cleansing Shampoo, 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/s/h/shampo_props_ky0ozlvydza60eyc.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:399,
    rating:5.0,
},
{
    title:"Milky Soft Face Cream With Murumuru Butter for Babies, 60 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/_/m/_milky_soft_face_cream_.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:199,
    rating:4.9,
},
{
    title:"Deeply Nourishing Body Wash for babies, 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/b/o/body-wash_probs_ui8gwmtjnj2sahbz.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:399,
    rating:4.8,
},
{
    title:"Moisturizing Bathing Bar Soap For Babies, pack of 2*75g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/f/d/fds_9573-props_qwhqvlzshodrynok.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:249,
    price:242,
    rating:4.8,
},
{
    title:"Agent Apple Body Wash for Kids with Apple & Oat Protein – 300 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/g/agent-apple-body-wash.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:598,
    price:299,
    rating:5.0,
},

{
    title:"Henna Shampoo with Henna and Deep Roast Coffee for Premature Greying - 250 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/h/e/henna-shampoo-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:349,
    rating:4.3,
    offer:"",
},
{
    title:"Henna Hair Oil with Henna & Coffee Oil for Premature Graying - 150 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/h/e/henna-oil-2.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:419,
    rating:4.3,
    offer:"",
},
{
    title:"Mamaearth Almond Hair Mask with Cold Pressed Almond Oil & Vitamin E for Healthy Hair Growth- 200 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/l/almond-hair-mask_2.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:599,
    rating:4.9,
    offer:"",
},
{
    title:"Onion Shampoo with Onion & Plant Keratin for Hair Fall Control - 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/_/o/_onion-oil-150ml_.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Onion Conditioner for Hair Growth and Hair Fall Control with Onion and Coconut, 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/n/onion_hair_mask_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Onion Conditioner for Hair Fall Control - 250ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-conditioner-250ml-with-ingredient_2.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Healthy Hair Combo : Happy Heads shampoo, 200ml and No More Tangles Conditioner, 200ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/s/h/shampoo-conditioner1800x1800_vdyppzbzvnlh2lix.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},

{
    title:"Major Mango Body Wash For Kids with Mango & Oat Protein - 300 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/m/a/mango-body-wash.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:598,
    price:299,
    rating:5.0,
},
{
    title:"Vitamin C Underarm Scrub with Vitamin C and Turmeric for Brighter Underarms – 50 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-underarm-scrub.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:5.0,
    offer:"",
},
{
    title:"Vitamin C Underarm Mask with Vitamin C & Turmeric for Brighter Underarms - 50 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-underarm-mask.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:5.0,
    offer:"",
},
{
    title:"Vitamin C Underarm Mask with Vitamin C & Turmeric for Brighter Underarms - 50 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-underarm-cream_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:5.0,
    offer:"",
},
{
    title:"Skin Radiance Body Care Kit - Ubtan Body Lotion & Vitamin C Body Lotion - (400 ml each)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin_c_and_ubtan.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Skin Refreshing & Soothing Body Care Kit - Rose Body Lotion + Vitamin C Body Lotion - (400 ml)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin_c_and_rose.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Charcoal Face Wash with Activated Charcoal and Coffee for Oil Control-250ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/h/charcoal-face-wash_1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:399,
    rating:4.8,
},
{
    title:"Ubtan Foaming Face Wash with Turmeric and Saffron for Tan Removal-150ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/2/_/2_4.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:399,
    rating:4.9,
},
{
    title:"Vitamin C Skincare Regimen Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-skincare-regimen-kit_mzka1kswpz0gem40.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:949,
    rating:5.0,
},
{
    title:"Charcoal Face Wash and Scrub Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/h/charcoal_wash_scrub_combo_o2pzkkjy9a04mza6.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:580,
    rating:5.0,
},

{
    title:"No More Tangles Conditioner for frizz free hair, 200ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/i/m/img_6889-with-prob_bjaylguyp3aj3wow.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:399,
    rating:4.9,
    offer:"",
},
{
    title:"Root Restore Hair Oil for hair fall reduction, 100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/i/m/img_6819-with-prob_dvpzp3xmm6xv2rhr.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"BhringAmla Hair Mask for Intense Hair Treatment - 200 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla_hair_mask_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:699,
    rating:4.9,
    offer:"",
},
{
    title:"Tea Tree Anti-Dandruff Hair Regime Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/t/e/tea-tree-kit-_bg_1200x1200_1_mcld7jogzpznwscj.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1297",
    price:908,
    rating:4.9,
    offer:"(30%off)",
},
{
    title:"Hair Fall Control Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/h/a/hair_fall_control_kit_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1396",
    price:977,
    rating:4.9,
    offer:"(30%off)",
},

{
    title:"Tea Tree Face Wash with Neem for Acne and Pimples-250ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/t/e/tea-tree-face-wash_2_290dsn6ifrjwimki.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:399,
    rating:4.8,
},
{
    title:"Acne Marks Reduction Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/1/2/1200x1200_poqqaktkr8d9andg.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:803,
    rating:4.9,
},
{
    title:"Super Strawberry Body Lotion for Kids With Strawberry & Shea Butter - 400 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/s/u/super-strawberry-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:798,
    price:399,
    rating:5.0,
},
{
    title:"Original Orange Body Lotion For Kids With Orange & Shea Butter - 400 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/r/original-orange-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:798,
    price:399,
    rating:5.0,
},
{
    title:"Major Mango Body Lotion For Kids with Mango Butter & Milk Protein - 400 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/m/a/major-mango-body-lotion-for-kids.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:798,
    price:399,
    rating:5.0,
},
{
    title:"Agent Apple Body Lotion for Kids with Apple & Oat Milk– 400 ml (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/g/agent-apple-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:798,
    price:399,
    rating:5.0,
},
{
    title:"Major Mango Body Lotion For Kids with Mango Butter & Milk Protein - 400 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/m/a/mango-body-lotions.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:399,
    rating:5.0,
},

{
    title:"Intense Hair Treatment Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/b/h/bhringamla-combo_msqe7ulfgyv85fsi.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1197",
    price:838,
    rating:4.9,
    offer:"(30%off)",
},
{
    title:"Anti-Hair Fall Spa Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/n/anti_hair_fall_spa_kit_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1197",
    price:868,
    rating:4.9,
    offer:"(30%off)",
},
{
    title:"Essential Anti-Hair Fall Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/n/anti-fall_regimen_kit_uges0reark90qp1c.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1696",
    price:1187,
    rating:4.9,
    offer:"(30%off)",
},
{
    title:"Tea Tree Shampoo and Onion Hair Oil Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/t/e/tea-tree-shampoo-_-onion-hair-oil_ezrrdrhuu1rkbagp.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹748",
    price:726,
    rating:4.9,
    offer:"(3%off)",
},

{
    title:"Brave Blueberry Body Lotion For Kids with Blueberry and Kokum Butter– 400 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/b/r/brave-blueberry-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:398,
    rating:5.0,
},
{
    title:"Skin Nourishing Body Care Combo - Ubtan Body Lotion + Rose Body Lotion  - (400 ml)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan_and_rose.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Vitamin C Body Lotion with Vitamin C & Honey for Radiant Skin - 400 ml   (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin_c_body_lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Ubtan Body Lotion with Turmeric & Kokum Butter for Glowing Skin - 400 ml  (Pack of 2)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan_body_lotion_7.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Rose Body Lotion with Rose Water & Milk for Deep Hydration (400 ml) - Pack of 2",
    imageurl:"https://honasa-mamaearth-production.imgix.net/r/o/rose_body_lotion_7.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Mamaearth ME Eau De Parfum For a Fragrance As Unique As You - 50 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/p/e/perfume-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:699,
    rating:4.9,
    offer:"",
},
{
    title:"Ubtan Nourishing Hair Removal Kit With Turmeric & Saffron for Hair Removal & Growth Reduction - 100+50 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-hair-removal-kit.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:449,
    rating:4.9,
    offer:"",
},
{
    title:"Tan Removal Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan_scurb_wash_u8j8uwoqnpyohxlf.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:580,
    rating:4.7,
},
{
    title:"Tan Removal Regimen Kit",
    imageurl:"https://honasa-mamaearth-production.imgix.net/t/a/tan-removal-regimen_10_whntawimnjpocnz9.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:1097,
    price:768,
    rating:4.8,
},
{
    title:"CoCo Face Wash with Coffee and Cocoa for Skin Awakening-100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/o/coco_face_wash_1.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:"",
    price:249,
    rating:4.8,
},
{
    title:"Tea Tree Face Wash and Charcoal Face Wash Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-charcoal-face-wash1200x1200_mrvx3mocrl4mlc0b.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:498,
    price:483,
    rating:4.6,
},
{
    title:"Ubtan Facewash for tan removal, Pack Of 2",
    imageurl:"https://honasa-mamaearth-production.imgix.net/6/6/66_tp8hhqpcdidxvumf.jpg?auto=compress&fit=scale&w=200&h=200",
    strikeprice:498,
    price:483,
    rating:4.8,
},

{
    title:"Onion Hair Serum and Onion Hair Oil Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/n/onion-hair-serum-_-onion-hair-oil_r0cve2co4dbojm9f.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹698",
    price:677,
    rating:4.8,
    offer:"(3%off)",
},
{
    title:"BhringAmla Shampoo and Conditioner Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/n/onion-shampoo-_-onion-conditioner_2hflieeliqkohq22.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹898",
    price:881,
    rating:4.8,
    offer:"(3%off)",
},
{
    title:"Argan Shampoo and Conditioner Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/r/argan_shampoo_and_conditionor_teypfi95redgibq8.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹698",
    price:677,
    rating:4.8,
    offer:"(3%off)",
},
{
    title:"Rose Body Lotion with Rose Water & Milk for Deep Hydration (400 ml) - Pack of 2",
    imageurl:"https://honasa-mamaearth-production.imgix.net/r/o/rose_body_lotion_7.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹799",
    price:518,
    rating:4.9,
    offer:"(35%off)",
},
{
    title:"Aloe Turmeric Gel for Skin and Hair 150ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/l/aloe_turmeric_gel_for_skin_and_hair_150ml_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:249,
    rating:4.9,
    offer:"",
},
{
    title:"Hair Fall Reduction Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/h/a/hairfall_reduction_combo_wvzngxlqxrvtnrvn.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹1299",
    price:1258,
    rating:4.9,
    offer:"(3%off)",
},
{
    title:"Onion Shampoo and Onion Hair Serum Combo",
    imageurl:"https://honasa-mamaearth-production.imgix.net/o/n/onion_shampoo_serum_combo_ruqrbph9uvkyx3my.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"₹698",
    price:668,
    rating:4.8,
    offer:"(3%off)",
},

{
    title:"Tea Tree Facewash for acne and pimples, Pack Of 2",
    imageurl:"https://honasa-mamaearth-production.imgix.net/1/2/12_2_ibepq3bigf22tx6z.jpg?auto=format&fit=crop&w=649&auto=compress",
    strikeprice:498,
    price:483,
    rating:4.9,
},
{
    title:"Apple Cider Vinegar Face Mask With Apple Cider Vinegar & Rosehip Oil for Clear and Glowing Skin – 100 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/c/acv_mask.jpg?auto=format&fit=crop&w=649&auto=compress",
    strikeprice:"",
    price:499,
    rating:5.0,
},
{
    title:"CoCo Face Wash with Coffee and Cocoa for Skin Awakening - 100ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/o/coco_face_wash_1.jpg?auto=format&fit=crop&w=649&auto=compress",
    strikeprice:"",
    price:249,
    rating:4.8,
},
{
    title:"Rose Body Lotion with Rose Water and Milk For Deep Hydration - 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/r/o/rose_body_lotion_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:399,
    rating:4.9,
    offer:"",
},
{
    title:"Vitamin C Body Lotion with Vitamin C and Honey for Radiant Skin - 400 ml ",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin_c_body_lotion_1_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:4.9,
    offer:"",
},
{
    title:"Ubtan Body Wash With Turmeric and Saffron for Glowing Skin - 300 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-body-wash-1_c7usn1sqjckdbdg5.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:4.9,
    offer:"",
},
{
    title:"Ubtan Nourishing Cold Cream with Turmeric & Saffron for Glowing Moisturization – 200 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/u/b/ubtan-cold-cream-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:4.9,
    offer:"",
},
{
    title:"Vitamin C Nourishing Cold Cream with Vitamin C & Honey for Illuminating Moisturization - 200 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/v/i/vitamin-c-cold-cream-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:4.9,
    offer:"",
},
{
    title:"CoCo Nourishing Cold Cream With Coffee and Vitamin E For Rich Moisturization - 200 g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/o/coco-cold-cream-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:299,
    rating:4.9,
    offer:"",
},
{
    title:"CoCo Body Lotion With Coffee and Cocoa for Intense Moisturization - 400ml ",
    imageurl:"https://honasa-mamaearth-production.imgix.net/c/o/coco_body_lotion_1.jpg?auto=compress&fit=scale&w=400&h=400",
    strike_price:"",
    price:399,
    rating:4.8,
    offer:"",
},
{
    title:"Agent Apple Body Lotion for Kids with Apple & Oat Milk– 400 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/a/g/agent_apple-body-lotion.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:399,
    rating:5.0,
},
{
    title:"Milky Soft Natural Lip Balm for Babies with Oats, Milk & Calendula – 4g",
    imageurl:"https://honasa-mamaearth-production.imgix.net/m/i/milky-soft-lip-balm-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:199,
    rating:4.9,
},
{
    title:"Milky Soft Face Cream With Murumuru Butter for Babies, 60 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/_/m/_milky_soft_face_cream_.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:199,
    rating:5.0,
},
{
    title:"Nourishing Bathing Bar Soap For Kids - ( Pack of 5, 75g Each)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/n/o/nourishing-bathing-bars_2_anb6wlrvagej2noa.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:499,
    rating:5.0,
},
{
    title:"Gentle Cleansing Shampoo, 400ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/s/h/shampo_props_ky0ozlvydza60eyc.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:199,
    rating:4.5,
},
{
    title:"Agent Apple Body Wash for Kids with Apple and Oat Protein - 300 ml",
    imageurl:"https://honasa-mamaearth-production.imgix.net/g/r/green_apple_baby_body_wash_1_1_.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:299,
    rating:4.9,
},
{
    title:"Plant-Based Diaper Pants for Babies – 9-14 kg (Size L - 30 Diapers)",
    imageurl:"https://honasa-mamaearth-production.imgix.net/d/i/diapers-l-1.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:0,
    price:699,
    rating:5.0,
},
{
    title:"Welcome Baby Essential Kit ",
    imageurl:"https://honasa-mamaearth-production.imgix.net/w/e/welcome-baby-essential-kit_iov2mdbdmdyyv6vu.jpg?auto=compress&fit=scale&w=400&h=400",
    strikeprice:1773,
    price:999,
    rating:5.0,
},
];
localStorage.setItem("all_data",JSON.stringify(allarr));